#.travis.yml

sudo: required
dist: trusty
language: node_js
node_js:
  - "10.2.1"

cache:
  directories:
    - $HOME/.npm
    - node_modules

install:
  - npm i --silent --no-optional

script:
  - npm run test:ci
  - npm run build:ci